import { NextRequest, NextResponse } from 'next/server'
import { ConvexHttpClient } from 'convex/browser'
import { api } from '@/convex/_generated/api'
import { Webhook } from 'svix'

// Initialize Convex client only at runtime
let convex: ConvexHttpClient | null = null

function getConvexClient(): ConvexHttpClient {
  if (!convex) {
    const url = process.env.NEXT_PUBLIC_CONVEX_URL
    if (!url) {
      throw new Error('NEXT_PUBLIC_CONVEX_URL environment variable is not set')
    }
    convex = new ConvexHttpClient(url)
  }
  return convex
}

// Verify webhook signature using Svix
function verifyWebhookSignature(payload: string, headers: Record<string, string>, secret: string): any {
  const svix = new Webhook(secret)
  return svix.verify(payload, headers)
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.text()
    const signature = request.headers.get('svix-signature') || ''
    const timestamp = request.headers.get('svix-timestamp') || ''
    const id = request.headers.get('svix-id') || ''

    // Verify webhook signature using Svix
    if (!process.env.CLERK_WEBHOOK_SECRET) {
      console.error('CLERK_WEBHOOK_SECRET is not set')
      return NextResponse.json(
        { error: 'Webhook secret not configured' },
        { status: 500 }
      )
    }

    try {
      const event = verifyWebhookSignature(body, {
        'svix-signature': signature,
        'svix-timestamp': timestamp,
        'svix-id': id,
      }, process.env.CLERK_WEBHOOK_SECRET)
      
      const { type, data } = event

      console.log(`Received webhook event: ${type}`, { 
        userId: data.id || data.user_id,
        timestamp: new Date().toISOString()
      })

      // Process webhook events
      switch (type) {
        case 'user.created':
          // Sync new user to Convex
          await getConvexClient().mutation(api.users.upsertUser, {
            clerkId: data.id,
            firstName: data.first_name,
            lastName: data.last_name,
            email: data.email_addresses[0]?.email_address || '',
            imageUrl: data.image_url,
            isAutoGenerated: false, // Mark as webhook-created user
          })
          console.log(`✅ User created successfully: ${data.id}`)
          break

        case 'user.updated':
          // Update user in Convex
          await getConvexClient().mutation(api.users.upsertUser, {
            clerkId: data.id,
            firstName: data.first_name,
            lastName: data.last_name,
            email: data.email_addresses[0]?.email_address || '',
            imageUrl: data.image_url,
            isAutoGenerated: false, // Mark as webhook-created user
          })
          console.log(`User updated: ${data.id}`)
          break

        case 'user.deleted':
          // Remove user from Convex
          await getConvexClient().mutation(api.users.deleteUserByClerkId, {
            clerkId: data.id,
          })
          console.log(`✅ User deleted successfully: ${data.id}`)
          break

        case 'session.created':
          // Update last sign in when user signs in
          if (data.user_id) {
            await getConvexClient().mutation(api.users.updateLastSignIn, {
              clerkId: data.user_id,
            })
            console.log(`✅ Session created for user: ${data.user_id}`)
          }
          break

        default:
          console.log(`Unhandled webhook type: ${type}`)
      }

      return NextResponse.json({ success: true })
      
    } catch (verificationError) {
      console.error('Webhook signature verification failed:', verificationError)
      return NextResponse.json(
        { error: 'Invalid webhook signature' },
        { status: 401 }
      )
    }

  } catch (error) {
    console.error('Webhook processing error:', error)
    return NextResponse.json(
      { error: 'Webhook processing failed' },
      { status: 500 }
    )
  }
}
